
db:
  host: localhost
  port: 3306
  username: gorm
  password: gorm
  database: gorm

mq:
  host: localhost
  port: 9093

redis:
  host: localhost
  port: 6379


cos:
  url: https://<bucket>.cos.<region>.myqcloud.com
  secret_id:
  secret_key:
