
db:
  host: localhost
  port: 3306
  username: root
  password: root
  database: mini_tiktok

mq:
  host: localhost
  port: 9093

redis:
  host: localhost
  port: 6379

ftp:
  host: localhost
  port: 21
  username:
  password: