
db:
  host: localhost
  port: 3306
  username: gorm
  password: gorm
  database: gorm

mq:
  host: localhost
  port: 9093

redis:
  host: localhost
  port: 6379

ftp:
  host: localhost
  port: 21
  username: Anonymous
  password:

static:
  url: localhost:8080
