// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTComment = "t_comment"

// TComment mapped from table <t_comment>
type TComment struct {
	ID         int64     `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"` // 评论id
	UserID     int64     `gorm:"column:user_id;type:int(10) unsigned;not null" json:"user_id"`            // 用户id
	Content    string    `gorm:"column:content;type:text;not null" json:"content"`                        // 评论内容
	CreateDate time.Time `gorm:"column:create_date;type:datetime;not null" json:"create_date"`            // 评论发布日期，格式为mm-dd
	VideoID    int64     `gorm:"column:video_id;type:int(10) unsigned;not null" json:"video_id"`          // 视频id
}

// TableName TComment's table name
func (*TComment) TableName() string {
	return TableNameTComment
}
