// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTFavorite = "t_favorite"

// TFavorite mapped from table <t_favorite>
type TFavorite struct {
	ID      int64 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"` // 点赞id
	VideoID int64 `gorm:"column:video_id;type:int(10) unsigned;not null" json:"video_id"`          // 视频id
	UserID  int64 `gorm:"column:user_id;type:int(10) unsigned;not null" json:"user_id"`            // 用户id
	Status  bool  `gorm:"column:status;type:tinyint(1);not null" json:"status"`                    // 点赞状态(0为未点赞, 1为已点赞)
}

// TableName TFavorite's table name
func (*TFavorite) TableName() string {
	return TableNameTFavorite
}
