// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	videoservice "mini_tiktok/kitex_gen/videoservice"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PublishAction(ctx context.Context, Req *videoservice.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *videoservice.DouyinPublishActionResponse, err error)
	Feed(ctx context.Context, Req *videoservice.DouyinFeedRequest, callOptions ...callopt.Option) (r *videoservice.DouyinFeedResponse, err error)
	PublishList(ctx context.Context, Req *videoservice.DouyinPublishListRequest, callOptions ...callopt.Option) (r *videoservice.DouyinPublishListResponse, err error)
	FavoriteAction(ctx context.Context, Req *videoservice.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *videoservice.DouyinFavoriteActionResponse, err error)
	FavoriteList(ctx context.Context, Req *videoservice.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *videoservice.DouyinFavoriteListResponse, err error)
	CommentAction(ctx context.Context, Req *videoservice.DouyinCommentActionRequest, callOptions ...callopt.Option) (r *videoservice.DouyinCommentActionResponse, err error)
	CommentList(ctx context.Context, Req *videoservice.DouyinCommentListRequest, callOptions ...callopt.Option) (r *videoservice.DouyinCommentListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) PublishAction(ctx context.Context, Req *videoservice.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *videoservice.DouyinPublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishAction(ctx, Req)
}

func (p *kVideoServiceClient) Feed(ctx context.Context, Req *videoservice.DouyinFeedRequest, callOptions ...callopt.Option) (r *videoservice.DouyinFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, Req)
}

func (p *kVideoServiceClient) PublishList(ctx context.Context, Req *videoservice.DouyinPublishListRequest, callOptions ...callopt.Option) (r *videoservice.DouyinPublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishList(ctx, Req)
}

func (p *kVideoServiceClient) FavoriteAction(ctx context.Context, Req *videoservice.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *videoservice.DouyinFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteAction(ctx, Req)
}

func (p *kVideoServiceClient) FavoriteList(ctx context.Context, Req *videoservice.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *videoservice.DouyinFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteList(ctx, Req)
}

func (p *kVideoServiceClient) CommentAction(ctx context.Context, Req *videoservice.DouyinCommentActionRequest, callOptions ...callopt.Option) (r *videoservice.DouyinCommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, Req)
}

func (p *kVideoServiceClient) CommentList(ctx context.Context, Req *videoservice.DouyinCommentListRequest, callOptions ...callopt.Option) (r *videoservice.DouyinCommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, Req)
}
