// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messageservice

import (
	server "github.com/cloudwego/kitex/server"
	chatservice "mini_tiktok/kitex_gen/service/ChatService"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler chatservice.MessageService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
